apiVersion: batch/v1
kind: CronJob
metadata:
  name: collect-weather-data-cronjob
spec:
  schedule: "0 */6 * * *"  # Run every 6 hours
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: collect-weather-data
            image: weatheracr861.azurecr.io/weather-data-service:latest
            command: ["python", "collect_weather_data.py"]
            env:
            - name: DB_SERVER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_SERVER
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PASSWORD
          restartPolicy: OnFailure
