apiVersion: batch/v1
kind: Job
metadata:
  name: db-setup-job-final
spec:
  template:
    spec:
      containers:
      - name: db-setup
        image: weatheracr861.azurecr.io/weather-data-service:latest
        command: ["python", "create_tables.py"]
        env:
        - name: DB_SERVER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_SERVER
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_PASSWORD
      restartPolicy: Never
  backoffLimit: 4











